import { PageContainer } from "@/components/layout/PageContainer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal Disclaimer — Proof of Claim",
  description: "Important legal disclaimer for users of Proof of Claim.",
};

export default function DisclaimerPage() {
  return (
    <PageContainer narrow>
      <article className="space-y-8">
        <h1 className="text-3xl sm:text-4xl font-bold text-primary">
          Legal Disclaimer
        </h1>

        <div className="bg-surface rounded-2xl border border-border p-6 sm:p-8 space-y-6 text-text-primary leading-relaxed">
          <div className="bg-warning/10 rounded-xl p-5 border border-warning/20">
            <p className="font-semibold text-warning">Important Notice</p>
            <p className="mt-2 text-sm">
              Please read this disclaimer carefully before using Proof of Claim.
              By using this tool, you acknowledge and accept the following
              terms.
            </p>
          </div>

          <h2 className="text-xl font-semibold text-primary">
            Not Legal Advice
          </h2>
          <p>
            Proof of Claim is an educational resource and document generation
            tool. It does <strong>not</strong> provide legal advice and should
            not be treated as a substitute for professional legal counsel.
          </p>
          <p>
            The information provided by this tool is for general informational
            purposes only. While we strive for accuracy and base our content on
            established legal principles, laws and regulations change, and
            every situation is unique.
          </p>

          <h2 className="text-xl font-semibold text-primary">
            Your Responsibility
          </h2>
          <p>By using this tool, you acknowledge that:</p>
          <ul className="space-y-2 ml-1">
            {[
              "You are responsible for your own decisions and actions",
              "Documents generated are templates that you should review before sending",
              "You should seek independent legal advice for complex or high-value matters",
              "Using these documents does not guarantee any particular outcome",
              "Laws and regulations may have changed since the content was written",
              "This tool does not create a solicitor-client relationship",
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-primary mt-2.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-semibold text-primary">
            Educational Purpose
          </h2>
          <p>
            This tool is designed to educate you about your existing legal
            rights — rights that are already established in English common law,
            statute, and regulation. The concepts covered include:
          </p>
          <ul className="space-y-2 ml-1">
            {[
              "The burden of proof in civil matters",
              "Your rights under the UK General Data Protection Regulation (UK GDPR)",
              "The Data Protection Act 2018",
              "The Consumer Rights Act 2015",
              "Common law principles established through centuries of case law",
              "Specific regulations governing council tax, energy supply, and debt collection",
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-teal mt-2.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-semibold text-primary">
            Document Standards
          </h2>
          <p>
            All documents generated by this tool are written to be professional,
            measured, and appropriate for formal correspondence. They are
            designed to:
          </p>
          <ul className="space-y-2 ml-1">
            {[
              'Use conditional acceptance rather than outright refusal — "I\'ll pay once you prove I owe it"',
              "Reference specific legal provisions and regulations",
              "Maintain a tone that would be appropriate if read in court",
              "Avoid confrontational, aggressive, or legally questionable language",
              'Not use "freeman" terminology, sovereign citizen arguments, or capital letters conspiracy theories',
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-accent mt-2.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-semibold text-primary">
            Data Protection
          </h2>
          <p>
            Your privacy is paramount. Proof of Claim operates with the
            following data principles:
          </p>
          <ul className="space-y-2 ml-1">
            {[
              "Document generation happens in your browser — your data is not sent to our servers",
              "Guest mode stores data only in your browser's local storage",
              "If you create an account, your data is encrypted and stored securely",
              "We never share, sell, or monetise your personal information",
              "You can delete all your data at any time",
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-success mt-2.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-semibold text-primary">
            When to Seek Professional Help
          </h2>
          <p>
            While this tool can help with many common situations, you should
            consider seeking professional legal advice if:
          </p>
          <ul className="space-y-2 ml-1">
            {[
              "You're facing court proceedings that have already been issued",
              "The amount in dispute is significant (generally over £10,000)",
              "You're dealing with criminal matters (not civil disputes)",
              "Your situation involves complex contractual arrangements",
              "You've received a statutory demand or winding-up petition",
              "Bailiffs claim to have a warrant and are at your door",
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="w-1.5 h-1.5 rounded-full bg-warning mt-2.5 shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <div className="bg-background rounded-xl p-6 border border-border">
            <h2 className="text-xl font-semibold text-primary mb-3">
              Free Legal Resources in the UK
            </h2>
            <ul className="space-y-2 text-sm text-text-secondary">
              <li>
                <strong>Citizens Advice</strong> — Free legal guidance on debts,
                housing, and consumer issues
              </li>
              <li>
                <strong>StepChange</strong> — Free debt advice charity
              </li>
              <li>
                <strong>National Debtline</strong> — Free telephone debt advice
              </li>
              <li>
                <strong>LawWorks</strong> — Free legal advice clinics
              </li>
              <li>
                <strong>Gov.uk</strong> — Official guidance on your legal
                rights and obligations
              </li>
            </ul>
          </div>

          <p className="text-sm text-text-secondary border-t border-border pt-6">
            This disclaimer was last updated on 13 February 2026. We may update
            this disclaimer from time to time. Continued use of the tool
            constitutes acceptance of any changes.
          </p>
        </div>
      </article>
    </PageContainer>
  );
}
